version: "2"

services:

  mariadb:
    image: wodby/mariadb:10.5
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - 3306:3306

  php:
    image: wodby/drupal-php:8.1
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      SSMTP_MAILHUB: mailhog:1025
      PHP_SENDMAIL_PATH: '"/usr/bin/dos2unix -u | /usr/sbin/ssmtp -t -f"'
#      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/nginx:1.23
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/build
      NGINX_VHOST_PRESET: drupal8
    volumes:
      - ./:/var/www/html
    ports:
    - "8080:80"

  selenium:
    image: selenium/standalone-chrome:4.1.3
    environment:
      - DISPLAY=:99
      - VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"
    expose:
      - '4444'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
