views.filter.team_filter:
  type: views_filter
  label: 'The teams to filter by'
  mapping:
    value:
      type: sequence
      label: 'Teams'
      sequence:
        type: string
        label: 'Team'
